console.time('ur code took')
console.log("test")
console.log(4+1)
console.log(7)
console.log(true)
console.log([1, 2, 3, 4])
console.log({key: 'key', value: 20 })
console.table({key: 'key', value: 20 })
console.warn("im a warning")
// console.clear()
console.timeEnd('ur code took')
// console.assert(1>2, 'this is an error hence u cant proceed')
console.error("this is an error")